# Override config cho môi trường local
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/identity_db?options=-c+TimeZone%3DUTC
    username: learnhub
    password: learnhub123

  rabbitmq:
    host: localhost

  data:
    redis:
      host: localhost

server:
  timezone: UTC

# Verbose logging khi dev
logging:
  level:
    com.learnhub: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
