package com.learnhub.identity.service;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.sql.Date;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * Service class for create and verify Learnhub JWT
 * Distinguish with Cognito JWT:
 * - Cognito JWT: generated by AWS Cognito, used for authenticate with Identity Service (this service)
 * - Learnhub JWT: generated by this service, include role from DB, used for authenticate with other services (like Course Service, Payment Service, etc.)
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class JwtService {
    @Value("${jwt.secret}")
    private String jwtSecret;

    @Value("${jwt.access-token-expiry}")
    private long accessTokenExpiry;

    @Value("${jwt.refresh-token-expiry}")
    private long refreshTokenExpiry;

    // create access token with userId, email, role
    public String generateAccessToken(UUID userId, String email, String role) {
        return buildToken(
                Map.of(
                        "userId", userId.toString(),
                        "email", email,
                        "role", role,
                        "type", "access"
                ),
                accessTokenExpiry
        );
    }

    // create refresh token with userId
    public String generateRefreshToken(UUID userId) {
        return buildToken(
                Map.of(
                        "userId", userId.toString(),
                        "type", "refresh"
                ),
                refreshTokenExpiry
        );
    }
    
    // verify token and parse claims
    public Claims parseToken(String token) {
        return Jwts.parser()
                .verifyWith(getSigningKey())
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

    public boolean isTokenValid(String token) {
        try {
            parseToken(token);
            return true;
        } catch (JwtException | IllegalArgumentException e) {
            log.warn("Invalid JWT token: {}", e.getMessage());
            return false;
        }
    }

    public UUID getUserIdFromToken(String token) {
        return UUID.fromString(parseToken(token).get("userId", String.class));
    }

    public long getAccessTokenExpiry() {
        return accessTokenExpiry;
    }

    public long getRefreshTokenExpiry() {
        return refreshTokenExpiry;
    }

    // private helpers
    private String buildToken(Map<String, Object> claims, long expirySeconds) {
        Instant now = Instant.now();
        return Jwts.builder()
                .claims(claims)
                .issuedAt(Date.from(now))
                .expiration(Date.from(now.plusSeconds(expirySeconds))) // expiry in seconds
                .signWith(getSigningKey())
                .compact();
    }

    public SecretKey getSigningKey() {
        byte[] keyBytes = jwtSecret.getBytes(StandardCharsets.UTF_8);
        return Keys.hmacShaKeyFor(keyBytes);
    }
}
