spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/payment_db
    username: learnhub
    password: learnhub123

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6380

logging:
  level:
    com.learnhub: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG