# Override config cho môi trường local
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/user_db
    username: learnhub
    password: learnhub123
    hikari:
      connection-init-sql: "SET TimeZone='UTC'"

  rabbitmq:
    host: localhost

  data:
    redis:
      host: localhost

# Verbose logging khi dev
logging:
  level:
    com.learnhub: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
